<<<<<<< HEAD
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/ecology-db}
server.port=${PORT:8081}
=======
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/college-db}
>>>>>>> b04315625d454cc4971def376b0286725ae1dfbf
